name: CICD-moments

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [aws-ec2]
    strategy:
      matrix:
        maven: ['3.9.6' ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Maven ${{ matrix.maven }} Action
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: 17
          maven-version: ${{ matrix.maven }}
      - name: Build project
        run: |
          mvn clean package -DskipTests
          cp target/*.jar /home/ubuntu/app/app.jar

  deploy:
    needs: build
    runs-on: [aws-ec2]
    env:
      DATABASE_URL: ${{vars.DATABASE_URL}}
      DATABASE_USER: ${{vars.DATABASE_USER}}
      DATABASE_PASSWORD: ${{vars.DATABASE_PASSWORD}}
      SECRET_KEY: ${{vars.SECRET_KEY}}
      JWT_EXPIRATION: ${{vars.JWT_EXPIRATION}}
    steps:
      - name: Run systemctl
        run: sudo systemctl restart app.service