name: CICD-moments

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests

  deploy:
    needs: build
    runs-on: [aws-ec2]
    env:
      DATABASE_URL: ${{DATABASE_URL}}
      DATABASE_USER: ${{DATABASE_USER}}
      DATABASE_PASSWORD: ${{DATABASE_PASSWORD}}
      SECRET_KEY: ${{SECRET_KEY}}
      JWT_EXPIRATION: ${{JWT_EXPIRATION}}
    steps:
      - name: Copy file jar
        run: cp target/*.jar /home/ubuntu/app/app.jar
      - name: Run systemctl
        run: sudo systemctl restart app.service