name: CICD-moments

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: |
          mvn clean install -DskipTests
          cp target/*.jar /home/ubuntu/app/app.jar

  deploy:
    needs: build
    runs-on: [aws-ec2]
    env:
      DATABASE_URL: ${{vars.DATABASE_URL}}
      DATABASE_USER: ${{vars.DATABASE_USER}}
      DATABASE_PASSWORD: ${{vars.DATABASE_PASSWORD}}
      SECRET_KEY: ${{vars.SECRET_KEY}}
      JWT_EXPIRATION: ${{vars.JWT_EXPIRATION}}
    steps:
      - name: Run systemctl
        run: sudo systemctl restart app.service